### ISSUE TITLE
What technology should we use? Write your proficient languages/technology here

### ISSUE THREAD

**Issue by drproduck** [drproduck/Element-Analytics#2]
C++, Java
Python, MATLAB
not familiar with any frameworks

**Comment by ColeSakamoto** [comment]
Java and some C using Eclipse
Some Python using PyCharm

**Comment by LyNgnH** [comment]
Some suggestions:
- MEAN stack (Javascript) 
- LAMP stack (PHP)
- Django (Python) 
- Ruby On Rails (Ruby) 
- Play Framework (Java)
- Spring Framework (Java)

**Comment by LPx1** [comment]
Java
Some C 
No experience with frameworks

**Comment by weimengpu** [comment]
Django (Python)

**Comment by LyNgnH** [comment]
Django
