### ISSUE TITLE
check and limit upload file size when (before) saving on server

### ISSUE THREAD

**Issue by drproduck** [drproduck/Element-Analytics#42]
this is professor's issue
prevent user from uploading xxlarge file and server from crashing
check using POST?

**Comment by LyNgnH** [comment]
If we use POST, django only check the file size after the file is completely uploaded, the damage is done, so no point using django for this.
If we leave this task to frontend, i.e. javascript, some (bad) users can modify the code and by pass the check.
Only option I can think of is using apache server to do this at server level. I'm not sure if django server has this option, which is unlikely.
